# Generated by Django 2.2.8 on 2019-12-16 16:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='phones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=14)),
                ('type', models.IntegerField(choices=[(1, 'Fijo'), (2, 'Movil'), (3, 'Comercial')])),
            ],
        ),
        migrations.CreateModel(
            name='photos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(upload_to=None)),
                ('bigsize', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descriptionWarehouse', models.CharField(max_length=50)),
                ('MinimumStock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('businessname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('credit', models.BooleanField()),
                ('amount', models.IntegerField()),
                ('categoryProvider', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('phonesProvider', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.phones')),
                ('stateProvider', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.state')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=20)),
                ('creationDate', models.DateField(auto_now=True)),
                ('lastUpate', models.DateField(auto_now=True)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('isActive', models.BooleanField(default=False)),
                ('categoryProduct', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('photos', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='products.photos')),
                ('productProvider', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.provider')),
                ('warehouseProduct', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.warehouse')),
            ],
        ),
    ]
