# Generated by Django 2.2.8 on 2019-12-13 18:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='phones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=14)),
                ('type', models.IntegerField(choices=[(1, 'Fijo'), (2, 'Movil'), (3, 'Comercial')])),
            ],
        ),
        migrations.CreateModel(
            name='photos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(upload_to=None)),
                ('bigsize', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descriptionWarehouse', models.CharField(max_length=50)),
                ('MinimumStock', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='categorie_id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='date',
        ),
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
        migrations.AddField(
            model_name='products',
            name='categoryProduct',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AddField(
            model_name='products',
            name='creationDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='products',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='lastUpate',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='provider',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('businessname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('credit', models.BooleanField()),
                ('amount', models.IntegerField()),
                ('categoryProvider', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('phonesProvider', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.phones')),
                ('stateProvider', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.state')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='photos',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='products.photos'),
        ),
        migrations.AddField(
            model_name='products',
            name='productProvider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.provider'),
        ),
        migrations.AddField(
            model_name='products',
            name='warehouseProduct',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.warehouse'),
        ),
    ]
