# Generated by Django 2.2.8 on 2019-12-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='bigsize',
            field=models.ImageField(upload_to='static/img/bigsize'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='thumbnail',
            field=models.ImageField(upload_to='static/img/thumbnail'),
        ),
    ]
