# Generated by Django 2.2.8 on 2019-12-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191213_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
    ]
