# Generated by Django 2.2.8 on 2019-12-16 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191216_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='photos',
        ),
    ]
