# Generated by Django 2.2.8 on 2019-12-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_products_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='bigsize',
            field=models.ImageField(default=None, upload_to='static/img/bigsize'),
        ),
        migrations.AddField(
            model_name='products',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='static/img/thumbnail'),
        ),
    ]
