# Generated by Django 2.2.8 on 2019-12-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191216_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='bigsize',
            field=models.ImageField(blank=True, default=None, upload_to='static/img/bigsize'),
        ),
        migrations.AlterField(
            model_name='products',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, upload_to='static/img/thumbnail'),
        ),
    ]
