# Generated by Django 2.2.8 on 2019-12-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191216_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
