# Generated by Django 2.2.8 on 2019-12-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20191224_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
