# Generated by Django 2.2.8 on 2020-01-06 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20191224_1258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='photos',
        ),
        migrations.AddField(
            model_name='warehouses',
            name='address',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='warehouses',
            name='first_admin',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='warehouses',
            name='lastName_admin',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='warehouses',
            name='phones',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.phones'),
        ),
        migrations.RemoveField(
            model_name='products',
            name='warehouseProduct',
        ),
        migrations.AddField(
            model_name='products',
            name='warehouseProduct',
            field=models.ManyToManyField(to='products.warehouses'),
        ),
    ]
