# Generated by Django 2.2.8 on 2020-01-18 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200106_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['id']},
        ),
    ]
