# Generated by Django 2.2.8 on 2020-01-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_clients_details_sales_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='detail',
        ),
        migrations.AddField(
            model_name='sales',
            name='detail',
            field=models.ManyToManyField(to='products.details'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'vendedor'), (3, 'propietario'), (4, 'cliente')]),
        ),
    ]
